name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Source Code
      run: npm run build
    - name: Publish (If Updated Version)
      uses: pascalgn/npm-publish-action@1.3.8
      with:
        publish_args: "--access public"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}